# Generated by Django 6.0.4 on 2026-04-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='diagnosis_images/')),
                ('image_filename', models.CharField(max_length=255)),
                ('predicted_condition', models.CharField(choices=[('melanoma', 'Melanoma'), ('nevus', 'Nevus'), ('basal_cell_carcinoma', 'Basal Cell Carcinoma'), ('actinic_keratosis', 'Actinic Keratosis'), ('benign_keratosis', 'Benign Keratosis'), ('dermatofibroma', 'Dermatofibroma'), ('vascular_lesion', 'Vascular Lesion')], max_length=50)),
                ('confidence_score', models.FloatField()),
                ('all_predictions', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_id', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Diagnosis Result',
                'verbose_name_plural': 'Diagnosis Results',
                'ordering': ['-created_at'],
            },
        ),
    ]
