# Generated by Django 5.2.13 on 2026-05-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('first_line_treatment', models.TextField(help_text='Prescription/medical advice')),
                ('doctor_specialty', models.CharField(help_text='e.g., Dermatologist, Oncologist', max_length=200)),
                ('referral_needed', models.BooleanField(default=True, help_text='Does it require a GP referral?')),
                ('urgency_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20)),
            ],
        ),
    ]
