# Generated by Django 5.2.13 on 2026-05-03 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0002_disease'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=100)),
                ('confidence', models.FloatField(default=0.0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='diagnosis_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnosis.disease')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient Diagnosis',
                'verbose_name_plural': 'Patient Diagnoses',
                'ordering': ['-created_at'],
            },
        ),
    ]
