# Generated by Django 5.2.13 on 2026-05-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0003_patientdiagnosis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='first_line_treatment',
        ),
        migrations.AddField(
            model_name='disease',
            name='precautions',
            field=models.TextField(default='Consult your doctor for specific precautions.', help_text='List of precautions, one per line'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disease',
            name='prescription',
            field=models.TextField(default='Consult your doctor for treatment options.', help_text='Recommended medicines or treatment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disease',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disease',
            name='referral_needed',
            field=models.BooleanField(default=False, help_text='Requires GP referral?'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='urgency_level',
            field=models.CharField(choices=[('Low', 'Low - Can wait for routine appointment'), ('Medium', 'Medium - See doctor within 2 weeks'), ('High', 'High - Seek immediate medical attention')], default='Medium', max_length=20),
        ),
    ]
