# Generated by Django 5.2.13 on 2026-05-03 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0004_remove_disease_first_line_treatment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisDocumentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Document Created'), ('VIEWED', 'Document Viewed'), ('UPDATED', 'Document Updated'), ('SHARED', 'Document Shared'), ('DELETED', 'Document Deleted')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, help_text='Additional metadata about the action')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_logs', to='diagnosis.patientdiagnosis')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Diagnosis Document History',
                'verbose_name_plural': 'Diagnosis Document Histories',
                'ordering': ['-timestamp'],
            },
        ),
    ]
