# Generated by Django 5.2.13 on 2026-05-03 15:07

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_hospitalstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='patient_id',
            field=models.CharField(default=accounts.models.generate_patient_id, editable=False, max_length=20, null=True),
        ),
    ]
