# Generated by Django 5.2.13 on 2026-05-03 15:08

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customerprofile_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='patient_id',
            field=models.CharField(default=accounts.models.generate_patient_id, editable=False, max_length=20, unique=True),
        ),
    ]
