# Generated by Django 5.2.13 on 2026-05-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_hospital_admin_user_hospital_hospital_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='hospital_id',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
